# PREFIX_ variables can be overridden by setting them in the environment
# before calling this script, e.g.:
#   PREFIX_YAMBO=/custom/yambo/bin bash run.sh BSE
PREFIX_QE=${PREFIX_QE:-/home/bonacc_m/Codes/q-e-kcw/bin}
PREFIX_KCW=${PREFIX_KCW:-/home/bonacc_m/Codes/q-e-kcw/KCW}
PREFIX_YAMBO=${PREFIX_YAMBO:-/home/bonacc_m/Codes/yambo/bin}
PREFIX_K2Y=${PREFIX_K2Y:-.}

PATH=$PREFIX_QE:$PREFIX_YAMBO:$PATH

WORKDIR=`pwd`

# Select what to run
# Steps can be passed as arguments: bash run.sh DFT P2Y K2Y
# If no arguments are given, fall back to the default list below.
if [[ $# -gt 0 ]]; then
  RUN_STEPS=("$@")
else
  RUN_STEPS=("CLEAN" "DFT" "P2Y" "KOOPMANS" "K2Y" "BSE")
fi

run_step () {
  local step=$1
  for s in "${RUN_STEPS[@]}"; do
    [[ "$s" == "$step" ]] && return 0
  done
  return 1
}

# -------- CLEAN --------
# Usage: add "CLEAN" to RUN_STEPS, or run:  bash run.sh  with RUN_STEPS=("CLEAN")
# Removes all files generated by each step while preserving input files,
# pseudopotentials and the script itself.
if run_step "CLEAN"; then
  echo "Cleaning generated files..."

  # DFT: remove output files and the pw.x scratch directory
  rm -f  DFT/scf.out DFT/nscf.out
  rm -rf DFT/out/

  # P2Y: remove the SAVE symlink, yambo setup reports, LOG and the out symlink
  rm -f  P2Y/SAVE P2Y/out
  rm -f  P2Y/r_setup P2Y/r_setup_*
  rm -rf P2Y/LOG/

  # KOOPMANS: remove all generated output/data files; keep only input files
  find KOOPMANS/ -maxdepth 1 -type f \
    ! -name '*.in' \
    -delete
  rm -rf KOOPMANS/*

  # YAMBO/BSE: remove output databases, reports, the ndb.QP and the SAVE symlink
  rm -f  YAMBO/SAVE YAMBO/ndb.QP
  rm -f  YAMBO/r-* YAMBO/o-* YAMBO/r_* YAMBO/o_* YAMBO/o.*
  rm -rf YAMBO/LOG/
  rm -rf YAMBO/bse/

  # K2Y: remove any generated QP databases
  rm -f  K2Y/*.QP
  
  rm _scheduler-std*

  echo "...clean completed."
fi


# -------- DFT --------
if run_step "DFT"; then
  cd DFT
  
  echo "Running SCF..."
  $PARA_PREFIX pw.x -in scf.in > scf.out
  echo "...SCF completed, now running NSCF..."
  $PARA_PREFIX pw.x -in nscf.in > nscf.out
  echo "NSCF completed."
  cd ..
fi

cd $WORKDIR

# -------- P2Y / YAMBO --------
if run_step "P2Y"; then
  echo "Running p2y and yambo init..."
  cd P2Y/
  if [ ! -e out ]; then
    ln -s ../DFT/out out
  fi
  cd out/aiida.save
  $PARA_PREFIX p2y
  cd ../..
  if [ ! -e SAVE ]; then
    ln -s out/aiida.save/SAVE SAVE
  fi
  $PARA_PREFIX yambo
  echo "...p2y and yambo init completed."
  cd ..
fi

cd $WORKDIR

# -------- KOOPMANS --------
if run_step "KOOPMANS"; then
  cd $PREFIX_KCW/examples/example01
  echo "Running Koopmans example for DFPT..."
  ./run_example
  echo "Koopmans example completed."

  cd $WORKDIR
  cp -rf $PREFIX_KCW/examples/example01/results/* KOOPMANS/.
  echo "Koopmans results copied to KOOPMANS directory."
fi

cd $WORKDIR

# -------- K2Y --------
if run_step "K2Y"; then
  echo "Running k2y: generating Koopmans QP database..."
  k2y generate \
    --ns-db1   P2Y/SAVE/ns.db1 \
    --eval     KOOPMANS/Si.kcw-ham_proj.out \
    --pwinput  KOOPMANS/Si.scf.in \
    --output   K2Y/ndb.QP
  echo "...k2y completed. Output: K2Y/ndb.QP"
fi

cd $WORKDIR

# -------- BSE --------
if run_step "BSE"; then
  cd YAMBO
  echo "Running BSE..."
  if [ ! -e SAVE ]; then
    ln -s ../P2Y/SAVE SAVE
  fi
  if [ ! -e ndb.QP ]; then
    ln -s ../K2Y/ndb.QP ndb.QP
  fi
  $PARA_PREFIX yambo -F yambo.in -J bse
  echo "...BSE completed."
fi
